version: "3.8"

services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "9020:9020"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=flowerShop
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowerShop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
